### ISSUE TITLE
Error message when running checkSeatrackRVersion()

### ISSUE THREAD

**Issue by Fjellrev** [NINAnor/seatrack-db#18]
I get this error:

Error: invalid version specification ‘0.0.2.28","Authors@R: ","    person(\"Jens\", \"Åström\", , \"jens.astrom@nina.no\", role = c(\"aut\", \"cre\"),","           comment = c(ORCID = \"0000-0002-6114-0440\"))","Description: R utility functions for interaction with the seatrack database. ","License: GPL (\u003e= 3)","Encoding: UTF-8","Roxygen: list(markdown = TRUE)","RoxygenNote: 7.2.3","Suggests: ","    knitr,","    rmarkdown,","\t  tidyverse,","\t  dbplyr,","  \tR.rsp","Imports:","  \tDBI,","  \tRPostgres,","  \tggplot2,","  \ttibble,","  \tdbplyr,","  \treadr,","  \tlubridate\t","Depends:","    rlang","VignetteBuilder: ","\t  R.scp,","\t  knitr","    "],"stylingDirectives":[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]],"colorizedLines":null,"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":false,"configFilePath":null,"networkDependabotPath":"/NINAnor/seatrack-db/network/updates","dismissConfigurationNoticePath"

**Comment by jenast** [comment]
Fixed in https://github.com/NINAnor/seatrack-db/pull/19/commits/70ddbb263ccac522e33f19176a7b834ab2bd8c04
